### ISSUE TITLE
Problem in training

### ISSUE THREAD

**Issue by brenocg29** [shimisalant/rasor#1]
Im trying to use your model but when I try to train it, i receive a theano error: "InconsistencyError: Trying to reintroduce a removed node" any thought in why this is happening?

**Comment by shimisalant** [comment]
Hi,
Is your environment like the one on the [README file](https://github.com/shimisalant/RaSoR/blob/master/README.md)? Namely - the Theano version.
Also note your `.theanorc` file should be set up correctly, for example:
```
[global]
floatX = float32
device = cpu
warn_float64 = raise
assert_no_cpu_op = raise
[nvcc]
fastmath = True
[lib]
cnmem = 0.94
```

**Comment by brenocg29** [comment]
It was the theano config file, thank you very much
